### ISSUE TITLE
Setting Flipt configuration values

### ISSUE THREAD

**Issue by chasevida** [flipt-io/helm-charts#10]
Thanks for Flipt and the helm chart. Looking through the chart there doesn't seem to be a way to pass configuration values for `general`, `cache`, `database` and `server` etc. Relatively new to helm so maybe there is something obvious I've missed but I can't see anywhere to pass `env` values through the `values.yaml` or via a `set` parameter. Is this available and I'm just missing it or should I create a PR to add it? Thanks again.

**Comment by markphelps** [comment]
👋🏻 Hi @chasevida ! Thanks for trying out Flipt! I'm also relatively new to Helm so I'm probably not following the best practices yet.

I think you're right that it isn't very easy to customize the config right now via Helm. I've exposed a ConfigMap in the [template](https://github.com/flipt-io/helm-charts/blob/main/charts/flipt/templates/configmap.yaml) which gets mounted on the pod as a volume in a place that Flipt knows to look for configuration.. although from a Helm user perspective I'm not sure how easy it is to change the values of a ConfigMap.

I think the best course is for me to expose these as values in `values.yaml` and then load those into the config map for the best of both worlds? I'm going to do some research into other well-used projects and see how they have their charts setup, but if you have any advice / thoughts I'd love to hear!

Will get this fixed ASAP

**Comment by markphelps** [comment]
@chasevida update: I've got a PR #12 that should allow you to set env vars for the container, combining this with the [docs](https://flipt.io/docs/configuration#environment-variables) should allow you to override any default config without messing with configmaps.

please lmk what you think

**Comment by chasevida** [comment]
@markphelps thank you! I've just pulled down the latest chart and have successfully configured it via environment variables in the `values.yaml`. Really appreciate the project and the effort that goes into this - cheers 👍 🙇 .
