### ISSUE TITLE
Reference secret using envFrom as additional config values

### ISSUE THREAD

**Issue by nopasutsamp** [flipt-io/helm-charts#134]
**Feature Request:**

Reference the entire secret and merge to envs of the container.

_Specify in values.yaml_
```
flipt:
  secretName: foo-secret
```

_Will produce this in deployment_

```
envFrom:
  - secretRef:
      name: foo-secret
```

**Comment by GeorgeMac** [comment]
Would if work for you @nopasutsamp if we simply added `envFrom` and copied it into the deployment like so:
```yaml
flipt:
  envFrom:
  - secretRef:
      name: foo-secret
```

My thinking here is that folks can express any of the `envFrom` forms in this way.

**Comment by nopasutsamp** [comment]
> Would if work for you @nopasutsamp if we simply added `envFrom` and copied it into the deployment like so:
> 
> ```yaml
> flipt:
>   envFrom:
>   - secretRef:
>       name: foo-secret
> ```
> 
> My thinking here is that folks can express any of the `envFrom` forms in this way.

This is possible too, The code is just longer but it works perfectly the same. I am fine with either ways. Thanks @GeorgeMac
