### ISSUE TITLE
There's no template variable for setting the namespace

### ISSUE THREAD

**Issue by asemarian** [flipt-io/helm-charts#174]
I'm trying to install Flipt and scope it to a specific namespace, but I can't seem to do that? Any help regarding this would be greatly appreciated.

**Comment by asemarian** [comment]
Hey @GeorgeMac. I just submitted PR #176 with the required fix. The thing is, I use [cdk8s](https://cdk8s.io/docs/latest/) to import Helm charts; I don't use Helm directly. I'm not exactly sure how cdk8s uses `helm template` under the hood, but for whatever reason passing it a namespace doesn't make a difference: the resulting manifests are not scoped to a namespace. The PR fixes that problem.

**Comment by GeorgeMac** [comment]
No problem @asemarian ! Thanks for the explanation! Just need the version to be bumped in the PR and then we're all good to go.

**Comment by asemarian** [comment]
I appreciate it 🙏 The pull request should be ready to merge now.
