### ISSUE TITLE
There is no template for Ingress configuration

### ISSUE THREAD

**Issue by tomaszmichalowski** [flipt-io/helm-charts#48]
Values file have section regarding Ingress but there is missing template for Ingress configuration.

**Comment by tomaszmichalowski** [comment]
Example of good Ingress template file
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml

**Comment by GeorgeMac** [comment]
This should be available from `flipt-0.26.1` thanks to @tomaszmichalowski 🙏
