### ISSUE TITLE
Helm chart does not suppor init container

### ISSUE THREAD

**Issue by tomaszmichalowski** [flipt-io/helm-charts#68]
When making a helm upgrade there is no possibility to run `./trino migrate` to update DB.
The best solution would be to have an init container wich will perform migration before starting a new service.

**Comment by tomaszmichalowski** [comment]
I will think about a solution and propose a PR when got some free time.

**Comment by tomaszmichalowski** [comment]
Did not checked yet, but does migration itself return the proper exit code?

**Comment by GeorgeMac** [comment]
Could you elaborate on what you mean by proper exit code @tomaszmichalowski ?

Do you mean: does it return a non-zero exit code when it fails to perform migrations?

**Comment by charlesoconor** [comment]
Have a PR that should address this. Running the migration command in a helm hook. This is how I've done migration on some of my services at work, and it works well. The request was for an init container, but those will run any time a pod comes up, which could be fairly often if the HPA are flapping and has the potential to lock up the database if multiple migrations are run at the same time. Using a hook ensures that only 1 of these containers will run at any given time and only on initial deployment.

When he was asking about exit codes presumably means that `flipt migrate` will exit non zero on a failure which it does, so you'll know if the migration failed.

**Comment by GeorgeMac** [comment]
This was closed thanks to @charlesoconor contribution!
You can now have migrations happen automatically by enabling the following config flag:
https://github.com/flipt-io/helm-charts/blob/main/charts/flipt/values.yaml#L182
